### PR TITLE
Allow use of use_database in proxy_for classes

### PR DESCRIPTION
**Pull request by ellneal**
Due to the way the `prepare_database` function is currently implemented, it's not possible to have a class that calls `use_database` _and_ `proxy_for`.

``` ruby
class Company < CouchRest::Model::Base
  use_database 'companies'
  property :slug

  proxy_database_method :slug
  proxy_for :invoices
end

class Invoice < CouchRest::Model::Base
  proxied_by :company
end
```

In this example, the `proxy_database` method of `Company` will always return the same database as is used by the `Company` class itself, due to the implementation in [CouchRest::Model::Connection.prepare_database](https://github.com/couchrest/couchrest_model/blob/3ba0c4137ab336dcb177ae680ec85160482f2ef4/lib/couchrest/model/connection.rb#L34).

This PR makes the test case for this scenario fail and adds the ability to override the `@_use_database` instance variable in `Connection` module.

### CODE REVIEW

**Comment by islam-askar** [comment]
Thanks @ellneal 

When will this PR merged to the master?

**Comment by ellneal** [comment]
It's up to @samlown if or when this will be merged. For now @islam-askar, if you want to use all my changes you can just point at my fork:

```ruby
gem 'couchrest_model', git: 'https://github.com/ellneal/couchrest_model.git', branch: 'develop'
```

**Comment by islam-askar** [comment]
@ellneal Thank you

**Comment by samlown** [comment]
Thanks for this @ellneal! This PR is now conflicting. Would you have chance to merge? There might also be some tests missing as I can't see that anything is being checked.

**Comment by ellneal** [comment]
No problem @samlown, I'll sort the conflict out. As far as testing goes, I considered this PR more of a bug fix than feature addition, so I made the existing test cases for `proxy_for` fail in ab4eab4 without the changes I made in aca4dff. Is that ok?

**Comment by ellneal** [comment]
Conflict has been resolved.

**Comment by samlown** [comment]
This is fixed in #218 so will merge that version. Thanks @ellneal!

**Pull request closed without merging**
